spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  pool:
    minIdle: 1
    maxIdle: 10
    maxWait: 3
    maxActive: 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aaa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 1111

